FROM debian:latest
RUN apt-get update
# Webserver
RUN apt-get install -y apache2
RUN apt-get install -y apache2-utils

#Utils

RUN apt-get install -y nano
RUN apt-get install -y net-tools
RUN apt-get install -y netcat
RUN apt-get install -y curl
RUN apt-get install -y wget

#PHP
RUN apt-get install -y php
RUN apt-get install -y libapache2-mod-php
RUN apt-get install -y php-mysql
RUN apt-get install -y php-curl

#MySQL
RUN apt-get install -y mysql-server
RUN apt-get install -y mysql-client

#PHPMyAdmin
RUN apt-get install -y phpmyadmin

#Wordpress
RUN apt-get install -y wordpress

#SSL
RUN apt-get install -y openssl
RUN apt-get install -y ssl-cert
RUN apt-get install -y ca-certificates
RUN apt-get install -y certbot
RUN apt-get install -y python-certbot-apache

#SSH
RUN apt-get install -y openssh-server

RUN apt-get clean


RUN service apache2 start
EXPOSE 80 80
EXPOSE 443 443

